apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-ms
  namespace: ccoms
  labels:
    app: proxy-ms
spec:
  replicas: 2
  
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  
  selector:
    matchLabels:
      app: proxy-ms
  template:
    metadata:
      labels:
        app: proxy-ms
    spec:
      containers:
      - name: proxy-ms
        image: compucomm/organization-mgmt-system:proxy-server-service
        imagePullPolicy: Always
        ports:
        - containerPort: 8111
        env:
        - name: app.profile
          value: prod

        readinessProbe:
          httpGet:
            path: /
            port: 8111
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
---
apiVersion: v1
kind: Service
metadata:
  name: proxy
  namespace: ccoms
  labels:
    app: proxy-svc
spec:
  ports:
  - port: 8111
    protocol: TCP
  selector:
    app: proxy-ms

