apiVersion: v1
kind: Namespace
metadata:
   name: ccoms
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cfg-ms
  namespace: ccoms
  labels:
    app: cfg-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cfg-ms
  template:
    metadata:
      labels:
        app: cfg-ms
    spec:
      containers:
      - name: cfg-ms
        image: compucomm/organization-mgmt-system:config-server-service
        imagePullPolicy: Always
        ports:
        - containerPort: 8888
        env:
        - name: app.profile
          value: prod
---
apiVersion: v1
kind: Service
metadata:
  name: cfg
  namespace: ccoms
  labels:
    app: cfg-svc
spec:
  ports:
  - port: 8888
    protocol: TCP
  selector:
    app: cfg-ms

