apiVersion: v1
kind: Namespace
metadata:
   name: ccoms
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dept-ms
  namespace: ccoms
  labels:
    app: dept-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dept-ms
  template:
    metadata:
      labels:
        app: dept-ms
    spec:
      containers:
      - name: dept-ms
        image: compucomm/organization-mgmt-system:department-service
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        env:
        - name: app.profile
          value: prod
---
apiVersion: v1
kind: Service
metadata:
  name: dept
  namespace: ccoms
  labels:
    app: dept-svc
spec:
  ports:
  - port: 8081
    protocol: TCP
  selector:
    app: dept-ms

