apiVersion: v1
kind: Namespace
metadata:
   name: ccoms
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emp-ms
  namespace: ccoms
  labels:
    app: emp-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emp-ms
  template:
    metadata:
      labels:
        app: emp-ms
    spec:
      containers:
      - name: emp-ms
        image: compucomm/organization-mgmt-system:employee-service
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: app.profile
          value: prod
---
apiVersion: v1
kind: Service
metadata:
  name: emp
  namespace: ccoms
  labels:
    app: emp-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: emp-ms

