apiVersion: v1
kind: Namespace
metadata:
   name: ccoms
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-ms
  namespace: ccoms
  labels:
    app: proxy-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy-ms
  template:
    metadata:
      labels:
        app: proxy-ms
    spec:
      containers:
      - name: proxy-ms
        image: compucomm/organization-mgmt-system:proxy-server-service
        imagePullPolicy: Always
        ports:
        - containerPort: 8111
        env:
        - name: app.profile
          value: prod
---
apiVersion: v1
kind: Service
metadata:
  name: proxy
  namespace: ccoms
  labels:
    app: proxy-svc
spec:
  ports:
  - port: 8111
    protocol: TCP
  selector:
    app: proxy-ms

