---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: mongo
  labels:
    app: mongodb
spec:
  ports:
  - port: 27027
    targetPort: 27017
    protocol: TCP
    name: dbport
  selector:
    app: mongodb
  externalIPs:
  - 10.180.86.187
