spring:
  application:
    name: organization-microservice
  profiles:
    include:
    - ${app.profile}

server:
  servlet:
    path: /organization    
cloud:
  config:
    uri: http://localhost:8888
