apiVersion: v1
kind: Service
metadata:
  name: proxy-extsvc
  namespace: ccoms
  labels:
    app: proxy-ms
spec:
  ports:
  - port: 8111
    protocol: TCP
  selector:
    app: proxy-ms
  externalIPs:
  - 192.168.43.165

