kind: Deployment
metadata:
  name: dept-ms
  namespace: ccoms
  labels:
    app: dept-ms
spec:
  replicas: {{ APPS.DEPARTMENT.REPLICA }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 50%
  selector:
    matchLabels:
      app: dept-ms
  template:
    metadata:
      labels:
        app: dept-ms
    spec:
      containers:
      - name: dept-ms
        image: "{{ IMAGEPREFIX }}:{{ APPS.DEPARTMENT.IMAGE }}"
        imagePullPolicy: Always
        ports:
        - containerPort: {{ APPS.DEPARTMENT.CONTAINERPORT }}
        env:
        - name: app.profile
          value: {{ PROFILE }}
        readinessProbe:
          httpGet:
            path: {{ APPS.DEPARTMENT.READYNESSPROBEHTTPPATH }}
            port: {{ APPS.DEPARTMENT.CONTAINERPORT }}
          initialDelaySeconds: 120
          periodSeconds: 10
          successThreshold: 1
        livenessProbe:
          httpGet:
            path: {{ APPS.DEPARTMENT.LIVENESSPROBEHTTPPATH }}
            port: {{ APPS.DEPARTMENT.CONTAINERPORT }}
          initialDelaySeconds: 120
          periodSeconds: 10
          successThreshold: 1
