apiVersion: apps/v1
kind: Deployment
metadata:
  name: org-ms
  namespace: ccoms
  labels:
    app: org-ms
spec:
  replicas: {{ APPS.ORGANIZATION.REPLICA }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 50%
  selector:
    matchLabels:
      app: org-ms
  template:
    metadata:
      labels:
        app: org-ms
    spec:
      containers:
      - name: org-ms
        image: "{{ IMAGEPREFIX }}:{{ APPS.ORGANIZATION.IMAGE }}"
        imagePullPolicy: Always
        ports:
        - containerPort: {{ APPS.ORGANIZATION.CONTAINERPORT }}
        env:
        - name: app.profile
          value: {{ PROFILE }}
        readinessProbe:
          httpGet:
            path: {{ APPS.ORGANIZATION.READYNESSPROBEHTTPPATH }}
            port: {{ APPS.ORGANIZATION.CONTAINERPORT }}
          initialDelaySeconds: 120
          periodSeconds: 10
          successThreshold: 1
        livenessProbe:
          httpGet:
            path: {{ APPS.ORGANIZATION.LIVENESSPROBEHTTPPATH }}
            port: {{ APPS.ORGANIZATION.CONTAINERPORT }}
          initialDelaySeconds: 120
          periodSeconds: 10
          successThreshold: 1
