apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: {{ namespace }}
  labels:
    app: mongodb
spec:
  replicas: {{ DB.MONGO.REPLICA }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 50%
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: 'mongo:latest'
        imagePullPolicy: Always
        ports:
        - containerPort: {{ DB.MONGO.PORT }}
        env:
        - name: MONGO_INITDB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mongodb
              key: database-name
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb
              key: database-user
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb
              key: database-password
