apiVersion: v1
kind: Service
metadata:
   name: dept
   namespace: ccoms
   labels:
      app: dept-svc
spec:
   ports:
   -  port: {{ APPS.DEPARTMENT.CONTAINERPORT }}
      protocol: TCP
   selector:
      app: dept-ms

