apiVersion: v1
kind: Service
metadata:
   name: emp
   namespace: ccoms
   labels:
      app: emp-svc
spec:
   ports:
   -  port: {{ APPS.EMPLOYEE.CONTAINERPORT }}
      protocol: TCP
   selector:
      app: emp-ms

